name: Satis Build On Push

on:
  push:
    paths:
      - satis.json
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-build
  cancel-in-progress: false

env:
  COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.TOKEN }}"}}'

jobs:
  satisBuild:
    name: Satis Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr

      - name: PHP version
        run: php --version

      - name: Validate Composer files
        run: composer validate

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer vendor directory
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: composer install

      - name: Checkout GitHub pages branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: gh-pages
          path: ./dist

      - name: Run Build
        run: composer run build

      - name: List files
        run: ls -lah ./dist

      - name: Commit web files
        run: |
          cd ./dist
          git config --local user.name "Newfold WordPress Team"
          git config --local user.email "wordpress-coe@newfold.com"
          git remote -v
          git add -A
          git commit -m "Satis build triggered by commit ${{ github.sha }}"
          git status
          cd -

      - name: Push changes
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # v0.8.0
        with:
          branch: gh-pages
          directory: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send message to ms teams
        uses: dhollerbach/actions.send-message-to-ms-teams@dfc95a402e5cef63a9dd790f8ae51f49951b6754 # v3
        with:
          webhook: '${{ secrets.INCOMING_WEBHOOK_URL }}'
          message: 'Satis updates deployed! Visit https://newfold-labs.github.io/satis/'
