name: Satis Build On Push

on:
  push:
    paths:
      - satis.json
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-build
  cancel-in-progress: false

env:
  COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.NEWFOLD_ACCESS_TOKEN }}"}}'

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  satisBuild:
    name: Satis Build
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required for actions/cache to restore and save caches.
      contents: write # Required to push commits to the gh-pages branch via ad-m/github-push-action.
    timeout-minutes: 30
    steps:

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr
        env:
          GITHUB_TOKEN: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}

      - name: PHP version
        run: php --version

      - name: Validate Composer files
        run: composer validate

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer vendor directory
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: composer install

      - name: Checkout GitHub pages branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: gh-pages
          path: ./dist

      - name: Run Build
        run: composer run satis:build

      - name: List files
        run: ls -lah ./dist

      - name: Commit web files
        run: |
          cd ./dist
          git config --local user.name "Newfold WordPress Team"
          git config --local user.email "wordpress-coe@newfold.com"
          git remote -v
          git add -A
          git commit -m "Satis build triggered by commit ${{ github.sha }}"
          git status
          cd -

      - name: Push changes
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # v1.3.0
        with:
          branch: gh-pages
          directory: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}

     
