name: Satis Build via Webhook

on: 
  repository_dispatch:
    types:
      - 'satis-build'
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-build
  cancel-in-progress: false

env:
  VENDOR: ${{ github.event.client_payload.vendor }}
  PACKAGE: ${{ github.event.client_payload.package }}
  VERSION: ${{ github.event.client_payload.version }}
  COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.NEWFOLD_ACCESS_TOKEN }}"}}'

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  satis-build:
    name: Satis Build
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required by actions/cache to restore and save caches.
      contents: write # Required to push commits to the gh-pages branch via ad-m/github-push-action and to create a repository_dispatch event via peter-evans/repository-dispatch.
    timeout-minutes: 30
    steps:

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr
        env:
          GITHUB_TOKEN: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}

      - name: PHP version
        run: php --version

      - name: Validate Composer files
        run: composer validate

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer vendor directory
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: composer install

      - name: Checkout GitHub pages branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: gh-pages
          path: ./dist

      - name: Run Build
        run: php -dmemory_limit=-1 vendor/bin/satis build --repository-url ${{ format('git@github.com:{0}/{1}.git', github.event.client_payload.vendor, github.event.client_payload.package) }} ./satis.json ./dist

      - name: List files
        run: ls -lah ./dist

      - name: Commit web files
        run: |
          cd ./dist
          git config --local user.name "Newfold WordPress Team"
          git config --local user.email "wordpress-coe@newfold.com"
          git remote -v
          git add -A
          git commit -m "Satis build triggered by release $VERSION of $VENDOR/$PACKAGE"
          git status
          cd -

      - name: Push changes
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # v1.3.0
        with:
          branch: gh-pages
          directory: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          event-type: 'package-released'
          client-payload: >-
            {
              "vendor": "$VENDOR",
              "package": "$PACKAGE",
              "version": "$VENDOR"
            }
