name: Create a PR for Bluehost module updates

on:
  repository_dispatch:
    types:
      - 'package-released'

env:
  VENDOR: ${{ github.event.client_payload.vendor }}
  PACKAGE: ${{ github.event.client_payload.package }}
  VERSION: ${{ github.event.client_payload.version }}
  ORIGIN_REPO: "${{ github.event.client_payload.vendor }}/${{ github.event.client_payload.package }}"
  REMOTE_REPO: "bluehost/bluehost-wordpress-plugin"

jobs:
  update-modules:
    name: Update Modules
    runs-on: ubuntu-latest
    if: ${{ startsWith( env.PACKAGE, 'wp-module-') }}
    steps:

      - name: Set module details
        run: |
          MODULE_SLUG=${PACKAGE/wp-module-/}
          MODULE_NAME=${MODULE_SLUG/-/ } | sed 's/[^ ]\+/\L\u&/g'
          BRANCH_NAME="update/${MODULE_SLUG}-module-to-${VERSION}"
          echo "MODULE_SLUG=$MODULE_SLUG" >> $GITHUB_ENV
          echo "MODULE_NAME=$MODULE_NAME" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Checkout brand plugin
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REMOTE_REPO }}
          ref: develop
          token: ${{ secrets.TOKEN }}
          path: './brand-plugin'

      - name: Check if module is used in the brand plugin
        id: requires
        uses: notiz-dev/github-action-json-property@master
        with:
          path: './brand-plugin/composer.json'
          prop_path: 'require.${{ env.VENDOR }}/${{ env.PACKAGE }}'

      - run: |
          if [ -n "${{ steps.requires.outputs.propStr }}" ]; then
            echo "IS_MODULE_USED=true" >> $GITHUB_ENV
          else
            echo "IS_MODULE_USED=false" >> $GITHUB_ENV
          fi

      - name: Checkout a new branch
        if: ${{ env.IS_MODULE_USED == 'true' }}
        run: |
          git -C ./brand-plugin checkout -b "${{ env.BRANCH_NAME }}"

      - name: Update module version
        if: ${{ env.IS_MODULE_USED == 'true' }}
        run: |
          composer require "${{ env.ORIGIN_REPO }}:${{ env.VERSION }}" -W --no-cache -d=./brand-plugin

      - name: Update module version
        if: ${{ env.IS_MODULE_USED == 'true' }} && ${{ env.PACKAGE == 'wp-module-ecommerce' }}
        run: |
          npm install github:newfold-labs/wp-module-ecommerce#${{ env.version }} --legacy-peer-deps -d=./brand-plugin

      - name: Commit changes
        if: ${{ env.IS_MODULE_USED == 'true' }}
        run: |
          cd ./brand-plugin
          git config --local user.name "Newfold WordPress Team"
          git config --local user.email "wordpress-coe@newfold.com"
          git remote -v
          git add -A
          git commit -m "Bump ${{ env.MODULE_NAME }} module to version ${{ env.VERSION }}"
          git status
          cd -

      - name: Push changes
        if: ${{ env.IS_MODULE_USED == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        if: ${{ env.IS_MODULE_USED == 'true' }}
        run: |
          gh pr create \
            --title "Update ${{ env.MODULE_NAME }} module to ${{ env.VERSION }}" \
            --body "This PR updates the ${{ env.MODULE_NAME }} module to version ${{ env.VERSION }}" \
            --repo ${{ env.REMOTE_REPO }} \
            --base develop \
            --head "${{ env.BRANCH_NAME }}"
